id: f7b6b8328f7a4efe8f726c27ec9aa677
initial_creation_type: ocr
source_metadata:
  volumes:
    267fb24ac2514c7ab5be10ec9ccb7630:
      base_file: v034.txt
      image_group_id: I1PD95879
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སྙིང་པོའི་སྒྲུབ་ཐབས།
      total_pages: 1734
      volume_number: 34
